### ISSUE TITLE
You can cheat "Control the hose-pipe" by dragging the water

### ISSUE THREAD

**Issue by spacevoyager78** [gcompris/GCompris-qt#296]
Hi!
A clever kid found out that he can cheat "Control the hose-pipe" by dragging the water from the left side of the hose straight to the right side! Then, he told everybody... :-) Is this fixable?

**Comment by petitlapin** [comment]
Hi,
thanks for the report!  Damn clever kid, they probably can already start a career as Quality Assurance! Yes, we'll take a look to fix it, hopefully for the next version

**Comment by Animtim** [comment]
Fixed for next release, thanks again for the report.

**Comment by petitlapin** [comment]
Fixed in https://invent.kde.org/education/gcompris/-/commit/ff0cda8c8ac0d18eb5fd1aa2f1418c56f2cc2431 :)

**Comment by spacevoyager78** [comment]
It is not fixed for me. Using 25.1, I can still click the red rectangle at the left end of the hose, drag it to the end of the hose and release it and after a couple of seconds the water appears.

**Comment by petitlapin** [comment]
Hi,
we created a new alpha version which contains the fix. The links can be found in the following mail: https://mail.kde.org/pipermail/gcompris-devel/2025-November/006351.html
Can you confirm we finally manage to solve the issue?

**Comment by petitlapin** [comment]
Wonderful! Thanks for validating. I'll close the issue now. We will release an official version in January (it will also contain the --hide-home-button option).
